### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by blizzarac** [realistschuckle/wpfchrometabs#1]
There is a problem with the animation. If you drag one tab to the left and drop just as the animation of the item below starts, then the item below is moved 2x tabWidth to the right. This is probably happening because ArrangeOverride is called before itemBelow.Complete.

**Comment by tonyjt** [comment]
I found a similar bug

**Comment by tonyjt** [comment]
It works if you set the duration to .01

From:StickyReanimate(shiftedTab, changed \* (this.currentTabWidth - this.overlap), .25);

To:    StickyReanimate(shiftedTab, changed \* (this.currentTabWidth - this.overlap), .01);
