### ISSUE TITLE
Handle "NewTab"

### ISSUE THREAD

**Issue by PedroCavaleiro** [realistschuckle/wpfchrometabs#3]
Hi, I've been using your tab control, I've added a few components for theming the ChromeTabItem but I'm having a problem. When I click the "add" button I can not set the properties to that new tab...
I can only set the properties on the tabs that I add programatically

Any help?

I also can not where the "add" button is linked to add the new tab... My ideia was when a new tab was created with the "add" button an event would be fired with the newTab as ChromeTabItem

So can you tell me the function that handles the newTab creation as ChromeTabItem

**Comment by realistschuckle** [comment]
@hitmanpt To be honest with you, it's been a while since I looked at this. You may want to take a look at https://github.com/sskodje/wpfchrometabs-mvvm which is more actively maintained.
